import { Fragment } from "react/cjs/react.production.min";
import "../styles/globals.css";
import Head from "next/head";
import Header from "../components/theme/Header";

function MyApp({ Component, pageProps }) {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Component {...pageProps} />

      <footer>this is footer</footer>
    </Fragment>
  );
}

export default MyApp;
